backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: postgresql-instance1.cg034hpkmmjt.eu-central-1.rds.amazonaws.com
    port: 5432
    database: mlflow
    user: mlflowuser
    password: Pa33w0rd!

artifactRoot:
  s3:
    enabled: true
    bucket: your-mlflow-artifacts-bucket
    path: ""  # Optional: S3 bucket folder
    awsAccessKeyId: ""  # Will use IAM role or secret
    awsSecretAccessKey: ""  # Will use IAM role or secret

extraEnvVars:
  AWS_DEFAULT_REGION: us-west-2
  MLFLOW_S3_ENDPOINT_URL: ""  # For MinIO compatibility
  MLFLOW_S3_IGNORE_TLS: "false"